/*
 * generated by Xtext 2.16.0
 */
package org.xtext.sdu.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.sdu.iot.ui.internal.IotActivator;

public class IoTUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return IotActivator.getInstance().getInjector("org.xtext.sdu.IoT");
	}

}
