/*
 * generated by Xtext 2.17.0
 */
package org.xtext.sdu.tests

import com.google.inject.Inject
import org.eclipse.xtext.generator.IFileSystemAccess
import org.eclipse.xtext.generator.IGenerator
import org.eclipse.xtext.generator.InMemoryFileSystemAccess
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.extensions.InjectionExtension
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.jupiter.api.Assertions
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.^extension.ExtendWith
import org.xtext.sdu.generator.IoTGenerator

@ExtendWith(InjectionExtension)
@InjectWith(IoTInjectorProvider)
class IoTParsingTest {
	@Inject ParseHelper<org.xtext.sdu.ioT.System> parseHelper
	
	protected def String removeFirstComment(InMemoryFileSystemAccess fsa) {
		val f = fsa.allFiles.get(IFileSystemAccess::DEFAULT_OUTPUT+"system.py").toString.trim
		f.substring(f.indexOf('\n')+1)
	}
	
	def baseImports() '''
	import pycom
	import time'''
	
	@Test
	def testSensorTypes() {
		val model = parseHelper.parse('''
        SensorTypes Ae, Be
        ''')
        val fsa = new InMemoryFileSystemAccess()
        
        val IoTGenerator = new IoTGenerator();
        IoTGenerator.doGenerate(model.eResource, fsa, null)
        val fileRead = removeFirstComment(fsa)
        Assertions.assertEquals(
        	'''
        	«baseImports»
        	import Ae from Ae
        	import Be from Be'''.toString,
        	fileRead
        )
	}
	
	
	@Test
	def testSensors() {
		val model = parseHelper.parse('''
		SensorTypes Ab
        Sensor Se of type Ab
        ''')
        val fsa = new InMemoryFileSystemAccess()
        
        val IoTGenerator = new IoTGenerator();
        IoTGenerator.doGenerate(model.eResource, fsa, null)
		val fileRead = removeFirstComment(fsa)
        Assertions.assertEquals(
        	'''
        	«baseImports»
        	import Ab from Ab
        	
        	Se = Ab()'''.toString,
        	fileRead
        )
	}
	
	@Test
	def testSensorGroups() {
		val model = parseHelper.parse('''
		SensorTypes Ab
		Sensor Se of type Ab
		Sensor De of type Ab
		SensorGroup Az include Se, De
        ''')
        val fsa = new InMemoryFileSystemAccess()
        
        val IoTGenerator = new IoTGenerator();
        IoTGenerator.doGenerate(model.eResource, fsa, null)
		val fileRead = removeFirstComment(fsa)
        Assertions.assertEquals(
        	'''
        	«baseImports»
        	import Ab from Ab
        	
        	Se = Ab()
        	De = Ab()
        	
        	Az = [Se,De]'''.toString,
        	fileRead
        )
	}
	
	
	@Test
	def testDeviceTypes() {
		val model = parseHelper.parse('''
        DeviceTypes Ae, Be
        ''')
        val fsa = new InMemoryFileSystemAccess()
        
        val IoTGenerator = new IoTGenerator();
        IoTGenerator.doGenerate(model.eResource, fsa, null)
		val fileRead = removeFirstComment(fsa)
        Assertions.assertEquals(
        	'''
        	«baseImports»
        	import Ae from Ae
        	import Be from Be'''.toString,
        	fileRead
        )
	}
	
	@Test
	def testDevices() {
		val model = parseHelper.parse('''
		DeviceTypes Ab
        Device Se of type Ab
        ''')
        val fsa = new InMemoryFileSystemAccess()
        
        val IoTGenerator = new IoTGenerator();
        IoTGenerator.doGenerate(model.eResource, fsa, null)
		val fileRead = removeFirstComment(fsa)
        Assertions.assertEquals(
        	'''
        	«baseImports»
        	import Ab from Ab
        	
        	Se = Ab()'''.toString,
        	fileRead
        )
	}
	
	@Test
	def testSensorGetMethod() {
		val model = parseHelper.parse('''
		SensorTypes Ab
		SensorGetMethod ab(ba,ca,da) for type Ab
        ''')
        val fsa = new InMemoryFileSystemAccess()
        
        val IoTGenerator = new IoTGenerator();
        IoTGenerator.doGenerate(model.eResource, fsa, null)
        val fileRead = removeFirstComment(fsa)
        Assertions.assertEquals(
        	'''
        	«baseImports»
        	import Ab from Ab
        	
        	
        	
        	getMethods = dict()
        	getMethods[Ab_ab(ba,ca,da)] = getattr(Ab,ab(ba,ca,da))'''.toString,fileRead)
	}
}
