/**
 * generated by Xtext 2.17.0
 */
package org.xtext.sdu.ide;

import org.xtext.sdu.ide.AbstractIoTIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class IoTIdeModule extends AbstractIoTIdeModule {
}
