/*
 * generated by Xtext 2.16.0
 */
package org.xtext.sdu.ui;

import com.google.inject.Injector;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.xtext.sdu.iot.ui.internal.IotActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class IoTExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(IotActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		IotActivator activator = IotActivator.getInstance();
		return activator != null ? activator.getInjector(IotActivator.ORG_XTEXT_SDU_IOT) : null;
	}

}
