/**
 * generated by Xtext 2.17.0
 */
package org.xtext.sdu;

import org.xtext.sdu.AbstractIoTRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class IoTRuntimeModule extends AbstractIoTRuntimeModule {
}
