/**
 * generated by Xtext 2.16.0
 */
package org.xtext.sdu.ioT;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Condition</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.sdu.ioT.IoTPackage#getCondition()
 * @model
 * @generated
 */
public interface Condition extends EObject
{
} // Condition
