/**
 * generated by Xtext 2.16.0
 */
package org.xtext.sdu.ioT;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Device</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.sdu.ioT.Device#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.sdu.ioT.Device#getType <em>Type</em>}</li>
 *   <li>{@link org.xtext.sdu.ioT.Device#getDevices <em>Devices</em>}</li>
 * </ul>
 *
 * @see org.xtext.sdu.ioT.IoTPackage#getDevice()
 * @model
 * @generated
 */
public interface Device extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.sdu.ioT.IoTPackage#getDevice_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.sdu.ioT.Device#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Type</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' reference.
   * @see #setType(DeviceType)
   * @see org.xtext.sdu.ioT.IoTPackage#getDevice_Type()
   * @model
   * @generated
   */
  DeviceType getType();

  /**
   * Sets the value of the '{@link org.xtext.sdu.ioT.Device#getType <em>Type</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' reference.
   * @see #getType()
   * @generated
   */
  void setType(DeviceType value);

  /**
   * Returns the value of the '<em><b>Devices</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Devices</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Devices</em>' reference.
   * @see #setDevices(EObject)
   * @see org.xtext.sdu.ioT.IoTPackage#getDevice_Devices()
   * @model
   * @generated
   */
  EObject getDevices();

  /**
   * Sets the value of the '{@link org.xtext.sdu.ioT.Device#getDevices <em>Devices</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Devices</em>' reference.
   * @see #getDevices()
   * @generated
   */
  void setDevices(EObject value);

} // Device
