/**
 * generated by Xtext 2.16.0
 */
package org.xtext.sdu.ioT;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see org.xtext.sdu.ioT.IoTPackage
 * @generated
 */
public interface IoTFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  IoTFactory eINSTANCE = org.xtext.sdu.ioT.impl.IoTFactoryImpl.init();

  /**
   * Returns a new object of class '<em>System</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>System</em>'.
   * @generated
   */
  System createSystem();

  /**
   * Returns a new object of class '<em>Sensor Type</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Sensor Type</em>'.
   * @generated
   */
  SensorType createSensorType();

  /**
   * Returns a new object of class '<em>Sensor Types</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Sensor Types</em>'.
   * @generated
   */
  SensorTypes createSensorTypes();

  /**
   * Returns a new object of class '<em>Sensor</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Sensor</em>'.
   * @generated
   */
  Sensor createSensor();

  /**
   * Returns a new object of class '<em>Sensor Group</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Sensor Group</em>'.
   * @generated
   */
  SensorGroup createSensorGroup();

  /**
   * Returns a new object of class '<em>Sensor Get Method</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Sensor Get Method</em>'.
   * @generated
   */
  SensorGetMethod createSensorGetMethod();

  /**
   * Returns a new object of class '<em>Method</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Method</em>'.
   * @generated
   */
  Method createMethod();

  /**
   * Returns a new object of class '<em>Device Type</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Device Type</em>'.
   * @generated
   */
  DeviceType createDeviceType();

  /**
   * Returns a new object of class '<em>Device Types</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Device Types</em>'.
   * @generated
   */
  DeviceTypes createDeviceTypes();

  /**
   * Returns a new object of class '<em>Device</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Device</em>'.
   * @generated
   */
  Device createDevice();

  /**
   * Returns a new object of class '<em>Server Type</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Server Type</em>'.
   * @generated
   */
  ServerType createServerType();

  /**
   * Returns a new object of class '<em>Server Types</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Server Types</em>'.
   * @generated
   */
  ServerTypes createServerTypes();

  /**
   * Returns a new object of class '<em>Server</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Server</em>'.
   * @generated
   */
  Server createServer();

  /**
   * Returns a new object of class '<em>Destination Type</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Destination Type</em>'.
   * @generated
   */
  DestinationType createDestinationType();

  /**
   * Returns a new object of class '<em>Destination Types</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Destination Types</em>'.
   * @generated
   */
  DestinationTypes createDestinationTypes();

  /**
   * Returns a new object of class '<em>Destination</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Destination</em>'.
   * @generated
   */
  Destination createDestination();

  /**
   * Returns a new object of class '<em>Fetch Data</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Fetch Data</em>'.
   * @generated
   */
  FetchData createFetchData();

  /**
   * Returns a new object of class '<em>Fetch Data Expression</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Fetch Data Expression</em>'.
   * @generated
   */
  FetchDataExpression createFetchDataExpression();

  /**
   * Returns a new object of class '<em>Fetch Data Condition</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Fetch Data Condition</em>'.
   * @generated
   */
  FetchDataCondition createFetchDataCondition();

  /**
   * Returns a new object of class '<em>Ip</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Ip</em>'.
   * @generated
   */
  Ip createIp();

  /**
   * Returns a new object of class '<em>Portnumber</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Portnumber</em>'.
   * @generated
   */
  Portnumber createPortnumber();

  /**
   * Returns a new object of class '<em>Time</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Time</em>'.
   * @generated
   */
  Time createTime();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  IoTPackage getIoTPackage();

} //IoTFactory
