/**
 * generated by Xtext 2.16.0
 */
package org.xtext.sdu.ioT;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.sdu.ioT.IoTFactory
 * @model kind="package"
 * @generated
 */
public interface IoTPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "ioT";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/sdu/IoT";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "ioT";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  IoTPackage eINSTANCE = org.xtext.sdu.ioT.impl.IoTPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.sdu.ioT.impl.SystemImpl <em>System</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.sdu.ioT.impl.SystemImpl
   * @see org.xtext.sdu.ioT.impl.IoTPackageImpl#getSystem()
   * @generated
   */
  int SYSTEM = 0;

  /**
   * The feature id for the '<em><b>System</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SYSTEM__SYSTEM = 0;

  /**
   * The number of structural features of the '<em>System</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SYSTEM_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.sdu.ioT.impl.SensorTypeImpl <em>Sensor Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.sdu.ioT.impl.SensorTypeImpl
   * @see org.xtext.sdu.ioT.impl.IoTPackageImpl#getSensorType()
   * @generated
   */
  int SENSOR_TYPE = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SENSOR_TYPE__NAME = 0;

  /**
   * The number of structural features of the '<em>Sensor Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SENSOR_TYPE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.sdu.ioT.impl.SensorTypesImpl <em>Sensor Types</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.sdu.ioT.impl.SensorTypesImpl
   * @see org.xtext.sdu.ioT.impl.IoTPackageImpl#getSensorTypes()
   * @generated
   */
  int SENSOR_TYPES = 2;

  /**
   * The feature id for the '<em><b>Types</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SENSOR_TYPES__TYPES = 0;

  /**
   * The number of structural features of the '<em>Sensor Types</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SENSOR_TYPES_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.sdu.ioT.impl.SensorImpl <em>Sensor</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.sdu.ioT.impl.SensorImpl
   * @see org.xtext.sdu.ioT.impl.IoTPackageImpl#getSensor()
   * @generated
   */
  int SENSOR = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SENSOR__NAME = 0;

  /**
   * The feature id for the '<em><b>Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SENSOR__TYPE = 1;

  /**
   * The number of structural features of the '<em>Sensor</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SENSOR_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.sdu.ioT.impl.SensorGroupImpl <em>Sensor Group</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.sdu.ioT.impl.SensorGroupImpl
   * @see org.xtext.sdu.ioT.impl.IoTPackageImpl#getSensorGroup()
   * @generated
   */
  int SENSOR_GROUP = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SENSOR_GROUP__NAME = 0;

  /**
   * The feature id for the '<em><b>Sensors</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SENSOR_GROUP__SENSORS = 1;

  /**
   * The number of structural features of the '<em>Sensor Group</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SENSOR_GROUP_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.sdu.ioT.impl.SensorGetMethodImpl <em>Sensor Get Method</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.sdu.ioT.impl.SensorGetMethodImpl
   * @see org.xtext.sdu.ioT.impl.IoTPackageImpl#getSensorGetMethod()
   * @generated
   */
  int SENSOR_GET_METHOD = 5;

  /**
   * The feature id for the '<em><b>Method</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SENSOR_GET_METHOD__METHOD = 0;

  /**
   * The feature id for the '<em><b>Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SENSOR_GET_METHOD__TYPE = 1;

  /**
   * The number of structural features of the '<em>Sensor Get Method</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SENSOR_GET_METHOD_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.sdu.ioT.impl.MethodImpl <em>Method</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.sdu.ioT.impl.MethodImpl
   * @see org.xtext.sdu.ioT.impl.IoTPackageImpl#getMethod()
   * @generated
   */
  int METHOD = 6;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METHOD__NAME = 0;

  /**
   * The feature id for the '<em><b>Parameters</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METHOD__PARAMETERS = 1;

  /**
   * The number of structural features of the '<em>Method</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int METHOD_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.sdu.ioT.impl.DeviceTypeImpl <em>Device Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.sdu.ioT.impl.DeviceTypeImpl
   * @see org.xtext.sdu.ioT.impl.IoTPackageImpl#getDeviceType()
   * @generated
   */
  int DEVICE_TYPE = 7;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEVICE_TYPE__NAME = 0;

  /**
   * The number of structural features of the '<em>Device Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEVICE_TYPE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.sdu.ioT.impl.DeviceTypesImpl <em>Device Types</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.sdu.ioT.impl.DeviceTypesImpl
   * @see org.xtext.sdu.ioT.impl.IoTPackageImpl#getDeviceTypes()
   * @generated
   */
  int DEVICE_TYPES = 8;

  /**
   * The feature id for the '<em><b>Types</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEVICE_TYPES__TYPES = 0;

  /**
   * The number of structural features of the '<em>Device Types</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEVICE_TYPES_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.sdu.ioT.impl.DeviceImpl <em>Device</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.sdu.ioT.impl.DeviceImpl
   * @see org.xtext.sdu.ioT.impl.IoTPackageImpl#getDevice()
   * @generated
   */
  int DEVICE = 9;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEVICE__NAME = 0;

  /**
   * The feature id for the '<em><b>Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEVICE__TYPE = 1;

  /**
   * The feature id for the '<em><b>Devices</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEVICE__DEVICES = 2;

  /**
   * The number of structural features of the '<em>Device</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEVICE_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.sdu.ioT.impl.ServerTypeImpl <em>Server Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.sdu.ioT.impl.ServerTypeImpl
   * @see org.xtext.sdu.ioT.impl.IoTPackageImpl#getServerType()
   * @generated
   */
  int SERVER_TYPE = 10;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SERVER_TYPE__NAME = 0;

  /**
   * The number of structural features of the '<em>Server Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SERVER_TYPE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.sdu.ioT.impl.ServerTypesImpl <em>Server Types</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.sdu.ioT.impl.ServerTypesImpl
   * @see org.xtext.sdu.ioT.impl.IoTPackageImpl#getServerTypes()
   * @generated
   */
  int SERVER_TYPES = 11;

  /**
   * The feature id for the '<em><b>Types</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SERVER_TYPES__TYPES = 0;

  /**
   * The number of structural features of the '<em>Server Types</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SERVER_TYPES_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.sdu.ioT.impl.ServerImpl <em>Server</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.sdu.ioT.impl.ServerImpl
   * @see org.xtext.sdu.ioT.impl.IoTPackageImpl#getServer()
   * @generated
   */
  int SERVER = 12;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SERVER__NAME = 0;

  /**
   * The feature id for the '<em><b>Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SERVER__TYPE = 1;

  /**
   * The feature id for the '<em><b>Ip</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SERVER__IP = 2;

  /**
   * The feature id for the '<em><b>Port</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SERVER__PORT = 3;

  /**
   * The number of structural features of the '<em>Server</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SERVER_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.xtext.sdu.ioT.impl.DestinationTypeImpl <em>Destination Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.sdu.ioT.impl.DestinationTypeImpl
   * @see org.xtext.sdu.ioT.impl.IoTPackageImpl#getDestinationType()
   * @generated
   */
  int DESTINATION_TYPE = 13;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DESTINATION_TYPE__NAME = 0;

  /**
   * The number of structural features of the '<em>Destination Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DESTINATION_TYPE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.sdu.ioT.impl.DestinationTypesImpl <em>Destination Types</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.sdu.ioT.impl.DestinationTypesImpl
   * @see org.xtext.sdu.ioT.impl.IoTPackageImpl#getDestinationTypes()
   * @generated
   */
  int DESTINATION_TYPES = 14;

  /**
   * The feature id for the '<em><b>Types</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DESTINATION_TYPES__TYPES = 0;

  /**
   * The number of structural features of the '<em>Destination Types</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DESTINATION_TYPES_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.sdu.ioT.impl.DestinationImpl <em>Destination</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.sdu.ioT.impl.DestinationImpl
   * @see org.xtext.sdu.ioT.impl.IoTPackageImpl#getDestination()
   * @generated
   */
  int DESTINATION = 15;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DESTINATION__NAME = 0;

  /**
   * The feature id for the '<em><b>Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DESTINATION__TYPE = 1;

  /**
   * The number of structural features of the '<em>Destination</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DESTINATION_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.sdu.ioT.impl.FetchDataImpl <em>Fetch Data</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.sdu.ioT.impl.FetchDataImpl
   * @see org.xtext.sdu.ioT.impl.IoTPackageImpl#getFetchData()
   * @generated
   */
  int FETCH_DATA = 16;

  /**
   * The feature id for the '<em><b>Filter</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FETCH_DATA__FILTER = 0;

  /**
   * The feature id for the '<em><b>Device</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FETCH_DATA__DEVICE = 1;

  /**
   * The feature id for the '<em><b>Destination</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FETCH_DATA__DESTINATION = 2;

  /**
   * The feature id for the '<em><b>Con Exp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FETCH_DATA__CON_EXP = 3;

  /**
   * The number of structural features of the '<em>Fetch Data</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FETCH_DATA_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.xtext.sdu.ioT.impl.FetchDataExpressionImpl <em>Fetch Data Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.sdu.ioT.impl.FetchDataExpressionImpl
   * @see org.xtext.sdu.ioT.impl.IoTPackageImpl#getFetchDataExpression()
   * @generated
   */
  int FETCH_DATA_EXPRESSION = 17;

  /**
   * The feature id for the '<em><b>Duration</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FETCH_DATA_EXPRESSION__DURATION = 0;

  /**
   * The feature id for the '<em><b>Time Unit</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FETCH_DATA_EXPRESSION__TIME_UNIT = 1;

  /**
   * The number of structural features of the '<em>Fetch Data Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FETCH_DATA_EXPRESSION_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.sdu.ioT.impl.FetchDataConditionImpl <em>Fetch Data Condition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.sdu.ioT.impl.FetchDataConditionImpl
   * @see org.xtext.sdu.ioT.impl.IoTPackageImpl#getFetchDataCondition()
   * @generated
   */
  int FETCH_DATA_CONDITION = 18;

  /**
   * The feature id for the '<em><b>Condition</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FETCH_DATA_CONDITION__CONDITION = 0;

  /**
   * The number of structural features of the '<em>Fetch Data Condition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FETCH_DATA_CONDITION_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.sdu.ioT.impl.IpImpl <em>Ip</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.sdu.ioT.impl.IpImpl
   * @see org.xtext.sdu.ioT.impl.IoTPackageImpl#getIp()
   * @generated
   */
  int IP = 19;

  /**
   * The feature id for the '<em><b>Ip</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IP__IP = 0;

  /**
   * The number of structural features of the '<em>Ip</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IP_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.sdu.ioT.impl.PortnumberImpl <em>Portnumber</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.sdu.ioT.impl.PortnumberImpl
   * @see org.xtext.sdu.ioT.impl.IoTPackageImpl#getPortnumber()
   * @generated
   */
  int PORTNUMBER = 20;

  /**
   * The feature id for the '<em><b>Number</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PORTNUMBER__NUMBER = 0;

  /**
   * The number of structural features of the '<em>Portnumber</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PORTNUMBER_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.sdu.ioT.impl.TimeImpl <em>Time</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.sdu.ioT.impl.TimeImpl
   * @see org.xtext.sdu.ioT.impl.IoTPackageImpl#getTime()
   * @generated
   */
  int TIME = 21;

  /**
   * The feature id for the '<em><b>Time</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TIME__TIME = 0;

  /**
   * The number of structural features of the '<em>Time</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TIME_FEATURE_COUNT = 1;


  /**
   * Returns the meta object for class '{@link org.xtext.sdu.ioT.System <em>System</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>System</em>'.
   * @see org.xtext.sdu.ioT.System
   * @generated
   */
  EClass getSystem();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.sdu.ioT.System#getSystem <em>System</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>System</em>'.
   * @see org.xtext.sdu.ioT.System#getSystem()
   * @see #getSystem()
   * @generated
   */
  EReference getSystem_System();

  /**
   * Returns the meta object for class '{@link org.xtext.sdu.ioT.SensorType <em>Sensor Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Sensor Type</em>'.
   * @see org.xtext.sdu.ioT.SensorType
   * @generated
   */
  EClass getSensorType();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.sdu.ioT.SensorType#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.sdu.ioT.SensorType#getName()
   * @see #getSensorType()
   * @generated
   */
  EAttribute getSensorType_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.sdu.ioT.SensorTypes <em>Sensor Types</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Sensor Types</em>'.
   * @see org.xtext.sdu.ioT.SensorTypes
   * @generated
   */
  EClass getSensorTypes();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.sdu.ioT.SensorTypes#getTypes <em>Types</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Types</em>'.
   * @see org.xtext.sdu.ioT.SensorTypes#getTypes()
   * @see #getSensorTypes()
   * @generated
   */
  EReference getSensorTypes_Types();

  /**
   * Returns the meta object for class '{@link org.xtext.sdu.ioT.Sensor <em>Sensor</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Sensor</em>'.
   * @see org.xtext.sdu.ioT.Sensor
   * @generated
   */
  EClass getSensor();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.sdu.ioT.Sensor#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.sdu.ioT.Sensor#getName()
   * @see #getSensor()
   * @generated
   */
  EAttribute getSensor_Name();

  /**
   * Returns the meta object for the reference '{@link org.xtext.sdu.ioT.Sensor#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Type</em>'.
   * @see org.xtext.sdu.ioT.Sensor#getType()
   * @see #getSensor()
   * @generated
   */
  EReference getSensor_Type();

  /**
   * Returns the meta object for class '{@link org.xtext.sdu.ioT.SensorGroup <em>Sensor Group</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Sensor Group</em>'.
   * @see org.xtext.sdu.ioT.SensorGroup
   * @generated
   */
  EClass getSensorGroup();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.sdu.ioT.SensorGroup#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.sdu.ioT.SensorGroup#getName()
   * @see #getSensorGroup()
   * @generated
   */
  EAttribute getSensorGroup_Name();

  /**
   * Returns the meta object for the reference list '{@link org.xtext.sdu.ioT.SensorGroup#getSensors <em>Sensors</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Sensors</em>'.
   * @see org.xtext.sdu.ioT.SensorGroup#getSensors()
   * @see #getSensorGroup()
   * @generated
   */
  EReference getSensorGroup_Sensors();

  /**
   * Returns the meta object for class '{@link org.xtext.sdu.ioT.SensorGetMethod <em>Sensor Get Method</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Sensor Get Method</em>'.
   * @see org.xtext.sdu.ioT.SensorGetMethod
   * @generated
   */
  EClass getSensorGetMethod();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.sdu.ioT.SensorGetMethod#getMethod <em>Method</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Method</em>'.
   * @see org.xtext.sdu.ioT.SensorGetMethod#getMethod()
   * @see #getSensorGetMethod()
   * @generated
   */
  EReference getSensorGetMethod_Method();

  /**
   * Returns the meta object for the reference '{@link org.xtext.sdu.ioT.SensorGetMethod#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Type</em>'.
   * @see org.xtext.sdu.ioT.SensorGetMethod#getType()
   * @see #getSensorGetMethod()
   * @generated
   */
  EReference getSensorGetMethod_Type();

  /**
   * Returns the meta object for class '{@link org.xtext.sdu.ioT.Method <em>Method</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Method</em>'.
   * @see org.xtext.sdu.ioT.Method
   * @generated
   */
  EClass getMethod();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.sdu.ioT.Method#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.sdu.ioT.Method#getName()
   * @see #getMethod()
   * @generated
   */
  EAttribute getMethod_Name();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.sdu.ioT.Method#getParameters <em>Parameters</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Parameters</em>'.
   * @see org.xtext.sdu.ioT.Method#getParameters()
   * @see #getMethod()
   * @generated
   */
  EAttribute getMethod_Parameters();

  /**
   * Returns the meta object for class '{@link org.xtext.sdu.ioT.DeviceType <em>Device Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Device Type</em>'.
   * @see org.xtext.sdu.ioT.DeviceType
   * @generated
   */
  EClass getDeviceType();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.sdu.ioT.DeviceType#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.sdu.ioT.DeviceType#getName()
   * @see #getDeviceType()
   * @generated
   */
  EAttribute getDeviceType_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.sdu.ioT.DeviceTypes <em>Device Types</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Device Types</em>'.
   * @see org.xtext.sdu.ioT.DeviceTypes
   * @generated
   */
  EClass getDeviceTypes();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.sdu.ioT.DeviceTypes#getTypes <em>Types</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Types</em>'.
   * @see org.xtext.sdu.ioT.DeviceTypes#getTypes()
   * @see #getDeviceTypes()
   * @generated
   */
  EReference getDeviceTypes_Types();

  /**
   * Returns the meta object for class '{@link org.xtext.sdu.ioT.Device <em>Device</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Device</em>'.
   * @see org.xtext.sdu.ioT.Device
   * @generated
   */
  EClass getDevice();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.sdu.ioT.Device#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.sdu.ioT.Device#getName()
   * @see #getDevice()
   * @generated
   */
  EAttribute getDevice_Name();

  /**
   * Returns the meta object for the reference '{@link org.xtext.sdu.ioT.Device#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Type</em>'.
   * @see org.xtext.sdu.ioT.Device#getType()
   * @see #getDevice()
   * @generated
   */
  EReference getDevice_Type();

  /**
   * Returns the meta object for the reference '{@link org.xtext.sdu.ioT.Device#getDevices <em>Devices</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Devices</em>'.
   * @see org.xtext.sdu.ioT.Device#getDevices()
   * @see #getDevice()
   * @generated
   */
  EReference getDevice_Devices();

  /**
   * Returns the meta object for class '{@link org.xtext.sdu.ioT.ServerType <em>Server Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Server Type</em>'.
   * @see org.xtext.sdu.ioT.ServerType
   * @generated
   */
  EClass getServerType();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.sdu.ioT.ServerType#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.sdu.ioT.ServerType#getName()
   * @see #getServerType()
   * @generated
   */
  EAttribute getServerType_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.sdu.ioT.ServerTypes <em>Server Types</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Server Types</em>'.
   * @see org.xtext.sdu.ioT.ServerTypes
   * @generated
   */
  EClass getServerTypes();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.sdu.ioT.ServerTypes#getTypes <em>Types</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Types</em>'.
   * @see org.xtext.sdu.ioT.ServerTypes#getTypes()
   * @see #getServerTypes()
   * @generated
   */
  EReference getServerTypes_Types();

  /**
   * Returns the meta object for class '{@link org.xtext.sdu.ioT.Server <em>Server</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Server</em>'.
   * @see org.xtext.sdu.ioT.Server
   * @generated
   */
  EClass getServer();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.sdu.ioT.Server#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.sdu.ioT.Server#getName()
   * @see #getServer()
   * @generated
   */
  EAttribute getServer_Name();

  /**
   * Returns the meta object for the reference '{@link org.xtext.sdu.ioT.Server#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Type</em>'.
   * @see org.xtext.sdu.ioT.Server#getType()
   * @see #getServer()
   * @generated
   */
  EReference getServer_Type();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.sdu.ioT.Server#getIp <em>Ip</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Ip</em>'.
   * @see org.xtext.sdu.ioT.Server#getIp()
   * @see #getServer()
   * @generated
   */
  EReference getServer_Ip();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.sdu.ioT.Server#getPort <em>Port</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Port</em>'.
   * @see org.xtext.sdu.ioT.Server#getPort()
   * @see #getServer()
   * @generated
   */
  EReference getServer_Port();

  /**
   * Returns the meta object for class '{@link org.xtext.sdu.ioT.DestinationType <em>Destination Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Destination Type</em>'.
   * @see org.xtext.sdu.ioT.DestinationType
   * @generated
   */
  EClass getDestinationType();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.sdu.ioT.DestinationType#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.sdu.ioT.DestinationType#getName()
   * @see #getDestinationType()
   * @generated
   */
  EAttribute getDestinationType_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.sdu.ioT.DestinationTypes <em>Destination Types</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Destination Types</em>'.
   * @see org.xtext.sdu.ioT.DestinationTypes
   * @generated
   */
  EClass getDestinationTypes();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.sdu.ioT.DestinationTypes#getTypes <em>Types</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Types</em>'.
   * @see org.xtext.sdu.ioT.DestinationTypes#getTypes()
   * @see #getDestinationTypes()
   * @generated
   */
  EReference getDestinationTypes_Types();

  /**
   * Returns the meta object for class '{@link org.xtext.sdu.ioT.Destination <em>Destination</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Destination</em>'.
   * @see org.xtext.sdu.ioT.Destination
   * @generated
   */
  EClass getDestination();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.sdu.ioT.Destination#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.sdu.ioT.Destination#getName()
   * @see #getDestination()
   * @generated
   */
  EAttribute getDestination_Name();

  /**
   * Returns the meta object for the reference '{@link org.xtext.sdu.ioT.Destination#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Type</em>'.
   * @see org.xtext.sdu.ioT.Destination#getType()
   * @see #getDestination()
   * @generated
   */
  EReference getDestination_Type();

  /**
   * Returns the meta object for class '{@link org.xtext.sdu.ioT.FetchData <em>Fetch Data</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Fetch Data</em>'.
   * @see org.xtext.sdu.ioT.FetchData
   * @generated
   */
  EClass getFetchData();

  /**
   * Returns the meta object for the reference '{@link org.xtext.sdu.ioT.FetchData#getFilter <em>Filter</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Filter</em>'.
   * @see org.xtext.sdu.ioT.FetchData#getFilter()
   * @see #getFetchData()
   * @generated
   */
  EReference getFetchData_Filter();

  /**
   * Returns the meta object for the reference '{@link org.xtext.sdu.ioT.FetchData#getDevice <em>Device</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Device</em>'.
   * @see org.xtext.sdu.ioT.FetchData#getDevice()
   * @see #getFetchData()
   * @generated
   */
  EReference getFetchData_Device();

  /**
   * Returns the meta object for the reference '{@link org.xtext.sdu.ioT.FetchData#getDestination <em>Destination</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Destination</em>'.
   * @see org.xtext.sdu.ioT.FetchData#getDestination()
   * @see #getFetchData()
   * @generated
   */
  EReference getFetchData_Destination();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.sdu.ioT.FetchData#getConExp <em>Con Exp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Con Exp</em>'.
   * @see org.xtext.sdu.ioT.FetchData#getConExp()
   * @see #getFetchData()
   * @generated
   */
  EReference getFetchData_ConExp();

  /**
   * Returns the meta object for class '{@link org.xtext.sdu.ioT.FetchDataExpression <em>Fetch Data Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Fetch Data Expression</em>'.
   * @see org.xtext.sdu.ioT.FetchDataExpression
   * @generated
   */
  EClass getFetchDataExpression();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.sdu.ioT.FetchDataExpression#getDuration <em>Duration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Duration</em>'.
   * @see org.xtext.sdu.ioT.FetchDataExpression#getDuration()
   * @see #getFetchDataExpression()
   * @generated
   */
  EReference getFetchDataExpression_Duration();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.sdu.ioT.FetchDataExpression#getTimeUnit <em>Time Unit</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Time Unit</em>'.
   * @see org.xtext.sdu.ioT.FetchDataExpression#getTimeUnit()
   * @see #getFetchDataExpression()
   * @generated
   */
  EAttribute getFetchDataExpression_TimeUnit();

  /**
   * Returns the meta object for class '{@link org.xtext.sdu.ioT.FetchDataCondition <em>Fetch Data Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Fetch Data Condition</em>'.
   * @see org.xtext.sdu.ioT.FetchDataCondition
   * @generated
   */
  EClass getFetchDataCondition();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.sdu.ioT.FetchDataCondition#getCondition <em>Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Condition</em>'.
   * @see org.xtext.sdu.ioT.FetchDataCondition#getCondition()
   * @see #getFetchDataCondition()
   * @generated
   */
  EAttribute getFetchDataCondition_Condition();

  /**
   * Returns the meta object for class '{@link org.xtext.sdu.ioT.Ip <em>Ip</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Ip</em>'.
   * @see org.xtext.sdu.ioT.Ip
   * @generated
   */
  EClass getIp();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.sdu.ioT.Ip#getIp <em>Ip</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Ip</em>'.
   * @see org.xtext.sdu.ioT.Ip#getIp()
   * @see #getIp()
   * @generated
   */
  EAttribute getIp_Ip();

  /**
   * Returns the meta object for class '{@link org.xtext.sdu.ioT.Portnumber <em>Portnumber</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Portnumber</em>'.
   * @see org.xtext.sdu.ioT.Portnumber
   * @generated
   */
  EClass getPortnumber();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.sdu.ioT.Portnumber#getNumber <em>Number</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Number</em>'.
   * @see org.xtext.sdu.ioT.Portnumber#getNumber()
   * @see #getPortnumber()
   * @generated
   */
  EAttribute getPortnumber_Number();

  /**
   * Returns the meta object for class '{@link org.xtext.sdu.ioT.Time <em>Time</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Time</em>'.
   * @see org.xtext.sdu.ioT.Time
   * @generated
   */
  EClass getTime();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.sdu.ioT.Time#getTime <em>Time</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Time</em>'.
   * @see org.xtext.sdu.ioT.Time#getTime()
   * @see #getTime()
   * @generated
   */
  EAttribute getTime_Time();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  IoTFactory getIoTFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.sdu.ioT.impl.SystemImpl <em>System</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.sdu.ioT.impl.SystemImpl
     * @see org.xtext.sdu.ioT.impl.IoTPackageImpl#getSystem()
     * @generated
     */
    EClass SYSTEM = eINSTANCE.getSystem();

    /**
     * The meta object literal for the '<em><b>System</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SYSTEM__SYSTEM = eINSTANCE.getSystem_System();

    /**
     * The meta object literal for the '{@link org.xtext.sdu.ioT.impl.SensorTypeImpl <em>Sensor Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.sdu.ioT.impl.SensorTypeImpl
     * @see org.xtext.sdu.ioT.impl.IoTPackageImpl#getSensorType()
     * @generated
     */
    EClass SENSOR_TYPE = eINSTANCE.getSensorType();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SENSOR_TYPE__NAME = eINSTANCE.getSensorType_Name();

    /**
     * The meta object literal for the '{@link org.xtext.sdu.ioT.impl.SensorTypesImpl <em>Sensor Types</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.sdu.ioT.impl.SensorTypesImpl
     * @see org.xtext.sdu.ioT.impl.IoTPackageImpl#getSensorTypes()
     * @generated
     */
    EClass SENSOR_TYPES = eINSTANCE.getSensorTypes();

    /**
     * The meta object literal for the '<em><b>Types</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SENSOR_TYPES__TYPES = eINSTANCE.getSensorTypes_Types();

    /**
     * The meta object literal for the '{@link org.xtext.sdu.ioT.impl.SensorImpl <em>Sensor</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.sdu.ioT.impl.SensorImpl
     * @see org.xtext.sdu.ioT.impl.IoTPackageImpl#getSensor()
     * @generated
     */
    EClass SENSOR = eINSTANCE.getSensor();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SENSOR__NAME = eINSTANCE.getSensor_Name();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SENSOR__TYPE = eINSTANCE.getSensor_Type();

    /**
     * The meta object literal for the '{@link org.xtext.sdu.ioT.impl.SensorGroupImpl <em>Sensor Group</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.sdu.ioT.impl.SensorGroupImpl
     * @see org.xtext.sdu.ioT.impl.IoTPackageImpl#getSensorGroup()
     * @generated
     */
    EClass SENSOR_GROUP = eINSTANCE.getSensorGroup();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SENSOR_GROUP__NAME = eINSTANCE.getSensorGroup_Name();

    /**
     * The meta object literal for the '<em><b>Sensors</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SENSOR_GROUP__SENSORS = eINSTANCE.getSensorGroup_Sensors();

    /**
     * The meta object literal for the '{@link org.xtext.sdu.ioT.impl.SensorGetMethodImpl <em>Sensor Get Method</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.sdu.ioT.impl.SensorGetMethodImpl
     * @see org.xtext.sdu.ioT.impl.IoTPackageImpl#getSensorGetMethod()
     * @generated
     */
    EClass SENSOR_GET_METHOD = eINSTANCE.getSensorGetMethod();

    /**
     * The meta object literal for the '<em><b>Method</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SENSOR_GET_METHOD__METHOD = eINSTANCE.getSensorGetMethod_Method();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SENSOR_GET_METHOD__TYPE = eINSTANCE.getSensorGetMethod_Type();

    /**
     * The meta object literal for the '{@link org.xtext.sdu.ioT.impl.MethodImpl <em>Method</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.sdu.ioT.impl.MethodImpl
     * @see org.xtext.sdu.ioT.impl.IoTPackageImpl#getMethod()
     * @generated
     */
    EClass METHOD = eINSTANCE.getMethod();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute METHOD__NAME = eINSTANCE.getMethod_Name();

    /**
     * The meta object literal for the '<em><b>Parameters</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute METHOD__PARAMETERS = eINSTANCE.getMethod_Parameters();

    /**
     * The meta object literal for the '{@link org.xtext.sdu.ioT.impl.DeviceTypeImpl <em>Device Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.sdu.ioT.impl.DeviceTypeImpl
     * @see org.xtext.sdu.ioT.impl.IoTPackageImpl#getDeviceType()
     * @generated
     */
    EClass DEVICE_TYPE = eINSTANCE.getDeviceType();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DEVICE_TYPE__NAME = eINSTANCE.getDeviceType_Name();

    /**
     * The meta object literal for the '{@link org.xtext.sdu.ioT.impl.DeviceTypesImpl <em>Device Types</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.sdu.ioT.impl.DeviceTypesImpl
     * @see org.xtext.sdu.ioT.impl.IoTPackageImpl#getDeviceTypes()
     * @generated
     */
    EClass DEVICE_TYPES = eINSTANCE.getDeviceTypes();

    /**
     * The meta object literal for the '<em><b>Types</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DEVICE_TYPES__TYPES = eINSTANCE.getDeviceTypes_Types();

    /**
     * The meta object literal for the '{@link org.xtext.sdu.ioT.impl.DeviceImpl <em>Device</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.sdu.ioT.impl.DeviceImpl
     * @see org.xtext.sdu.ioT.impl.IoTPackageImpl#getDevice()
     * @generated
     */
    EClass DEVICE = eINSTANCE.getDevice();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DEVICE__NAME = eINSTANCE.getDevice_Name();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DEVICE__TYPE = eINSTANCE.getDevice_Type();

    /**
     * The meta object literal for the '<em><b>Devices</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DEVICE__DEVICES = eINSTANCE.getDevice_Devices();

    /**
     * The meta object literal for the '{@link org.xtext.sdu.ioT.impl.ServerTypeImpl <em>Server Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.sdu.ioT.impl.ServerTypeImpl
     * @see org.xtext.sdu.ioT.impl.IoTPackageImpl#getServerType()
     * @generated
     */
    EClass SERVER_TYPE = eINSTANCE.getServerType();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SERVER_TYPE__NAME = eINSTANCE.getServerType_Name();

    /**
     * The meta object literal for the '{@link org.xtext.sdu.ioT.impl.ServerTypesImpl <em>Server Types</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.sdu.ioT.impl.ServerTypesImpl
     * @see org.xtext.sdu.ioT.impl.IoTPackageImpl#getServerTypes()
     * @generated
     */
    EClass SERVER_TYPES = eINSTANCE.getServerTypes();

    /**
     * The meta object literal for the '<em><b>Types</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SERVER_TYPES__TYPES = eINSTANCE.getServerTypes_Types();

    /**
     * The meta object literal for the '{@link org.xtext.sdu.ioT.impl.ServerImpl <em>Server</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.sdu.ioT.impl.ServerImpl
     * @see org.xtext.sdu.ioT.impl.IoTPackageImpl#getServer()
     * @generated
     */
    EClass SERVER = eINSTANCE.getServer();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SERVER__NAME = eINSTANCE.getServer_Name();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SERVER__TYPE = eINSTANCE.getServer_Type();

    /**
     * The meta object literal for the '<em><b>Ip</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SERVER__IP = eINSTANCE.getServer_Ip();

    /**
     * The meta object literal for the '<em><b>Port</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SERVER__PORT = eINSTANCE.getServer_Port();

    /**
     * The meta object literal for the '{@link org.xtext.sdu.ioT.impl.DestinationTypeImpl <em>Destination Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.sdu.ioT.impl.DestinationTypeImpl
     * @see org.xtext.sdu.ioT.impl.IoTPackageImpl#getDestinationType()
     * @generated
     */
    EClass DESTINATION_TYPE = eINSTANCE.getDestinationType();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DESTINATION_TYPE__NAME = eINSTANCE.getDestinationType_Name();

    /**
     * The meta object literal for the '{@link org.xtext.sdu.ioT.impl.DestinationTypesImpl <em>Destination Types</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.sdu.ioT.impl.DestinationTypesImpl
     * @see org.xtext.sdu.ioT.impl.IoTPackageImpl#getDestinationTypes()
     * @generated
     */
    EClass DESTINATION_TYPES = eINSTANCE.getDestinationTypes();

    /**
     * The meta object literal for the '<em><b>Types</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DESTINATION_TYPES__TYPES = eINSTANCE.getDestinationTypes_Types();

    /**
     * The meta object literal for the '{@link org.xtext.sdu.ioT.impl.DestinationImpl <em>Destination</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.sdu.ioT.impl.DestinationImpl
     * @see org.xtext.sdu.ioT.impl.IoTPackageImpl#getDestination()
     * @generated
     */
    EClass DESTINATION = eINSTANCE.getDestination();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DESTINATION__NAME = eINSTANCE.getDestination_Name();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DESTINATION__TYPE = eINSTANCE.getDestination_Type();

    /**
     * The meta object literal for the '{@link org.xtext.sdu.ioT.impl.FetchDataImpl <em>Fetch Data</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.sdu.ioT.impl.FetchDataImpl
     * @see org.xtext.sdu.ioT.impl.IoTPackageImpl#getFetchData()
     * @generated
     */
    EClass FETCH_DATA = eINSTANCE.getFetchData();

    /**
     * The meta object literal for the '<em><b>Filter</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FETCH_DATA__FILTER = eINSTANCE.getFetchData_Filter();

    /**
     * The meta object literal for the '<em><b>Device</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FETCH_DATA__DEVICE = eINSTANCE.getFetchData_Device();

    /**
     * The meta object literal for the '<em><b>Destination</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FETCH_DATA__DESTINATION = eINSTANCE.getFetchData_Destination();

    /**
     * The meta object literal for the '<em><b>Con Exp</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FETCH_DATA__CON_EXP = eINSTANCE.getFetchData_ConExp();

    /**
     * The meta object literal for the '{@link org.xtext.sdu.ioT.impl.FetchDataExpressionImpl <em>Fetch Data Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.sdu.ioT.impl.FetchDataExpressionImpl
     * @see org.xtext.sdu.ioT.impl.IoTPackageImpl#getFetchDataExpression()
     * @generated
     */
    EClass FETCH_DATA_EXPRESSION = eINSTANCE.getFetchDataExpression();

    /**
     * The meta object literal for the '<em><b>Duration</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FETCH_DATA_EXPRESSION__DURATION = eINSTANCE.getFetchDataExpression_Duration();

    /**
     * The meta object literal for the '<em><b>Time Unit</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FETCH_DATA_EXPRESSION__TIME_UNIT = eINSTANCE.getFetchDataExpression_TimeUnit();

    /**
     * The meta object literal for the '{@link org.xtext.sdu.ioT.impl.FetchDataConditionImpl <em>Fetch Data Condition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.sdu.ioT.impl.FetchDataConditionImpl
     * @see org.xtext.sdu.ioT.impl.IoTPackageImpl#getFetchDataCondition()
     * @generated
     */
    EClass FETCH_DATA_CONDITION = eINSTANCE.getFetchDataCondition();

    /**
     * The meta object literal for the '<em><b>Condition</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FETCH_DATA_CONDITION__CONDITION = eINSTANCE.getFetchDataCondition_Condition();

    /**
     * The meta object literal for the '{@link org.xtext.sdu.ioT.impl.IpImpl <em>Ip</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.sdu.ioT.impl.IpImpl
     * @see org.xtext.sdu.ioT.impl.IoTPackageImpl#getIp()
     * @generated
     */
    EClass IP = eINSTANCE.getIp();

    /**
     * The meta object literal for the '<em><b>Ip</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute IP__IP = eINSTANCE.getIp_Ip();

    /**
     * The meta object literal for the '{@link org.xtext.sdu.ioT.impl.PortnumberImpl <em>Portnumber</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.sdu.ioT.impl.PortnumberImpl
     * @see org.xtext.sdu.ioT.impl.IoTPackageImpl#getPortnumber()
     * @generated
     */
    EClass PORTNUMBER = eINSTANCE.getPortnumber();

    /**
     * The meta object literal for the '<em><b>Number</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PORTNUMBER__NUMBER = eINSTANCE.getPortnumber_Number();

    /**
     * The meta object literal for the '{@link org.xtext.sdu.ioT.impl.TimeImpl <em>Time</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.sdu.ioT.impl.TimeImpl
     * @see org.xtext.sdu.ioT.impl.IoTPackageImpl#getTime()
     * @generated
     */
    EClass TIME = eINSTANCE.getTime();

    /**
     * The meta object literal for the '<em><b>Time</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TIME__TIME = eINSTANCE.getTime_Time();

  }

} //IoTPackage
