/**
 * generated by Xtext 2.16.0
 */
package org.xtext.sdu.ioT;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Sensor Types</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.sdu.ioT.SensorTypes#getTypes <em>Types</em>}</li>
 * </ul>
 *
 * @see org.xtext.sdu.ioT.IoTPackage#getSensorTypes()
 * @model
 * @generated
 */
public interface SensorTypes extends EObject
{
  /**
   * Returns the value of the '<em><b>Types</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.sdu.ioT.SensorType}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Types</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Types</em>' containment reference list.
   * @see org.xtext.sdu.ioT.IoTPackage#getSensorTypes_Types()
   * @model containment="true"
   * @generated
   */
  EList<SensorType> getTypes();

} // SensorTypes
