/**
 * generated by Xtext 2.17.0
 */
package org.xtext.sdu.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.xtext.sdu.ui.AbstractIoTUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class IoTUiModule extends AbstractIoTUiModule {
  public IoTUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
